version: '4.0'

actions:
  generate_dataset:
    run: ehrql:v1 generate-dataset analysis/dataset_definition.py --output output/dataset.csv.gz
    outputs:
      highly_sensitive:
        dataset: output/dataset.csv.gz

  generate_measures:
    run: ehrql:v1 generate-measures analysis/default_measures.py --output output/example_measure1.csv.gz
    needs: 
    - generate_dataset
    outputs:
      highly_sensitive:
        dataset: output/example_measure1.csv.gz


#TO DO 
# merge_dataset: - action that runs R script to merge datasets
